---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 'https://807a35a0.ngrok.io/project/5d24eea529dc6bdb18e4e86b/webhook/forestry'
sections:
  - type: document
    label: Config
    path: config.yaml
    templates:
      - config
  - type: document
    label: Menu Configuration
    path: data/menu.yml
    templates:
      - menu
  - type: document
    label: Footer Configuration
    path: data/footer.yml
    templates:
      - footer
  - type: document
    label: Home
    path: content/_index.md
    templates:
      - home
  - type: directory
    path: content
    match: '**/*'
    exclude: '{_index.md,elements.md}'
    label: Pages
    create: all
    templates:
      - page
  - type: document
    label: Elements
    path: content/elements.md
    templates:
      - elements
upload_dir: static/images
public_path: /images
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
version: '0.47'
